const express = require('express');
const cors = require('cors');
const { YoutubeTranscript } = require('youtube-transcript');

const app = express();
const PORT = process.env.PORT || 3000;

// Enable CORS for all origins
app.use(cors());

// Parse JSON bodies (increased limit for base64 images)
app.use(express.json({ limit: '50mb' }));

// Health check
app.get('/', (req, res) => {
    res.json({ status: 'ok', message: 'Study Agent Backend is running' });
});

// Gemini Proxy Endpoint
app.post('/api/gemini', async (req, res) => {
    try {
        const { prompt, image, mimeType } = req.body;

        if (!prompt) {
            return res.status(400).json({ error: 'Prompt is required' });
        }

        const apiKey = process.env.GEMINI_KEY;
        if (!apiKey) {
            return res.status(500).json({ error: 'Server configuration error: GEMINI_KEY is missing' });
        }

        let contents = [];
        if (image && mimeType) {
            contents.push({
                parts: [
                    { text: prompt },
                    {
                        inlineData: {
                            mimeType: mimeType,
                            data: image
                        }
                    }
                ]
            });
        } else {
            contents.push({
                parts: [{ text: prompt }]
            });
        }

        const fetchResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ contents })
        });

        const data = await fetchResponse.json();

        if (!fetchResponse.ok || data.error) {
            const errMsg = data.error?.message || 'Failed to call Gemini API';
            return res.status(fetchResponse.status || 500).json({ error: errMsg });
        }

        const resultText = data.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!resultText) {
            return res.status(500).json({ error: 'No output was generated by the AI.' });
        }

        res.json({ result: resultText });
    } catch (err) {
        console.error('Gemini API fetch error:', err.message);
        res.status(500).json({ error: 'Internal server error while communicating with Gemini API.' });
    }
});

// Transcript endpoint
app.get('/transcript', async (req, res) => {
    const { video_id } = req.query;

    if (!video_id) {
        return res.status(400).json({ error: 'Missing video_id parameter' });
    }

    try {
        const transcriptItems = await YoutubeTranscript.fetchTranscript(video_id);

        if (!transcriptItems || transcriptItems.length === 0) {
            return res.status(404).json({ error: 'No transcript found for this video. It may not have captions.' });
        }

        const transcript = transcriptItems.map(item => item.text).join(' ');
        res.json({ transcript });
    } catch (err) {
        console.error('Transcript fetch error:', err.message);
        res.status(500).json({
            error: 'Failed to fetch transcript. The video may be private, age-restricted, or have no captions.'
        });
    }
});

app.listen(PORT, () => {
    console.log(`Study Agent API running on port ${PORT}`);
});
