const express = require('express');
const cors = require('cors');
const { YoutubeTranscript } = require('youtube-transcript');

const app = express();
const PORT = process.env.PORT || 3000;

// Enable CORS for all origins
app.use(cors());

// Parse JSON bodies (increased limit for base64 images)
app.use(express.json({ limit: '50mb' }));

// Health check
app.get('/', (req, res) => {
    res.json({ status: 'ok', message: 'Study Agent Backend is running' });
});

// Gemini API Key Rotation
const KEYS = [
    process.env.GEMINI_KEY,
    process.env.GEMINI_KEY_2
].filter(Boolean);

let keyIndex = 0;

function getNextKey() {
    keyIndex = (keyIndex + 1) % KEYS.length;
    return KEYS[keyIndex];
}

// Gemini Proxy Endpoint
app.post('/api/gemini', async (req, res) => {
    try {
        const { prompt, image, mimeType } = req.body;

        if (!prompt) {
            return res.status(400).json({ error: 'Prompt is required' });
        }

        if (KEYS.length === 0) {
            return res.status(500).json({ error: 'Server configuration error: No GEMINI_KEY configured' });
        }

        let contents = [];
        if (image && mimeType) {
            contents.push({
                parts: [
                    { text: prompt },
                    {
                        inlineData: {
                            mimeType: mimeType,
                            data: image
                        }
                    }
                ]
            });
        } else {
            contents.push({
                parts: [{ text: prompt }]
            });
        }

        // Try each key, rotating on 429 rate limit
        let lastError = null;
        for (let attempt = 0; attempt < KEYS.length; attempt++) {
            const apiKey = KEYS[keyIndex];

            const fetchResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ contents })
            });

            const data = await fetchResponse.json();

            // If rate limited, switch to next key and retry
            if (fetchResponse.status === 429) {
                console.log(`Key ${keyIndex} rate limited, switching to next key...`);
                lastError = data.error?.message || 'Rate limit exceeded';
                getNextKey();
                continue;
            }

            if (!fetchResponse.ok || data.error) {
                const errMsg = data.error?.message || 'Failed to call Gemini API';
                return res.status(fetchResponse.status || 500).json({ error: errMsg });
            }

            const resultText = data.candidates?.[0]?.content?.parts?.[0]?.text;
            if (!resultText) {
                return res.status(500).json({ error: 'No output was generated by the AI.' });
            }

            return res.json({ result: resultText });
        }

        // All keys exhausted
        return res.status(429).json({ error: `All API keys rate limited. ${lastError || 'Please try again later.'}` });
    } catch (err) {
        console.error('Gemini API fetch error:', err.message);
        res.status(500).json({ error: 'Internal server error while communicating with Gemini API.' });
    }
});

// Transcript endpoint
app.get('/transcript', async (req, res) => {
    const { video_id } = req.query;

    if (!video_id) {
        return res.status(400).json({ error: 'Missing video_id parameter' });
    }

    try {
        const transcriptItems = await YoutubeTranscript.fetchTranscript(video_id);

        if (!transcriptItems || transcriptItems.length === 0) {
            return res.status(404).json({ error: 'No transcript found for this video. It may not have captions.' });
        }

        const transcript = transcriptItems.map(item => item.text).join(' ');
        res.json({ transcript });
    } catch (err) {
        console.error('Transcript fetch error:', err.message);
        res.status(500).json({
            error: 'Failed to fetch transcript. The video may be private, age-restricted, or have no captions.'
        });
    }
});

app.listen(PORT, () => {
    console.log(`Study Agent API running on port ${PORT}`);
});

// Keep-alive ping for Render free instance
const RENDER_URL = 'https://study-agent-d26p.onrender.com';

setInterval(async () => {
    try {
        await fetch(RENDER_URL + '/');
        console.log('Keep-alive ping sent');
    } catch (e) {
        console.log('Ping failed:', e.message);
    }
}, 840000);
